[package]
name = "integration-empty"
version = "0.0.0"
authors = ["Dariusz Depta <DariuszDepta@users.noreply.github.com>"]
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "../src/lib.rs"

[dependencies]
empty = { path = ".." }
cosmwasm-schema = { version = "=3.0.11-rc.0" }
cosmwasm-std = { version = "=3.0.11-rc.0", features = ["iterator"] }
schemars = "0.8.12"

[dev-dependencies]
cosmwasm-vm = { version = "=3.0.11-rc.0", default-features = false, features = ["iterator"] }

# [patch.crates-io]
# cosmwasm-std = { path = "../../../packages/std", version = "=3.0.11-rc.0" }
# cosmwasm-schema = { path = "../../../packages/schema", version = "=3.0.11-rc.0" }
# cosmwasm-vm = { path = "../../../packages/vm", version = "=3.0.11-rc.0" }
