[package]
name = "integration-burner"
version = "0.0.0"
authors = ["Dariusz Depta <DariuszDepta@users.noreply.github.com>"]
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "../src/lib.rs"

[dependencies]
burner = { path = ".." }
cosmwasm-schema = { version = "=2.3.5" }
cosmwasm-std = { version = "=2.3.5", features = ["cosmwasm_1_4", "iterator"] }
schemars = "0.8.12"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-vm = { version = "=2.3.5", default-features = false, features = ["iterator"] }
