# See https://doc.mergify.io/configuration.html

pull_request_rules:
  - name: automerge to main with label automerge
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=automerge
      - -draft
      - label!=WIP
      # We need to list them all individually. Here is why: https://docs.mergify.com/conditions/#validating-all-status-checks
      # Also make sure to update this when the CI names change
      - "status-success=macOS"
      - "status-success=Windows"
      - "status-success=ci/circleci: arm64"
      - "status-success=ci/circleci: clippy-1.67.0"
      - "status-success=ci/circleci: clippy-1.68.2"
      - "status-success=ci/circleci: contract_burner"
      - "status-success=ci/circleci: contract_crypto_verify"
      - "status-success=ci/circleci: contract_cyberpunk"
      - "status-success=ci/circleci: contract_floaty"
      - "status-success=ci/circleci: contract_hackatom"
      - "status-success=ci/circleci: contract_hackatom"
      - "status-success=ci/circleci: contract_ibc_reflect"
      - "status-success=ci/circleci: contract_ibc_reflect_send"
      - "status-success=ci/circleci: contract_queue"
      - "status-success=ci/circleci: contract_reflect"
      - "status-success=ci/circleci: contract_staking"
      - "status-success=ci/circleci: contract_virus"
      # disabled temporarily because Rust version is too low
      # - "status-success=ci/circleci: coverage"
      - "status-success=ci/circleci: fmt"
      - "status-success=ci/circleci: fmt_extra"
      - "status-success=ci/circleci: package_check"
      - "status-success=ci/circleci: package_crypto"
      - "status-success=ci/circleci: package_schema"
      - "status-success=ci/circleci: package_schema_derive"
      - "status-success=ci/circleci: package_std"
      - "status-success=ci/circleci: package_storage"
      - "status-success=ci/circleci: package_vm"
      - "status-success=ci/circleci: package_vm_windows"
    actions:
      merge:
        method: merge
  - name: backport PRs to minor version branch
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          # Update this when going to a new minor version
          - "release/1.4"
        assignees:
          - "{{ author }}"
