# See https://doc.mergify.io/configuration.html

pull_request_rules:
  - name: automerge to master with label automerge
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=automerge
      - label!=WIP
      # We need to list them all individually. Here is why: https://doc.mergify.io/conditions.html#validating-all-status-check
      - "status-success=ci/circleci: package_schema"
      - "status-success=ci/circleci: package_std"
      - "status-success=ci/circleci: package_storage"
      - "status-success=ci/circleci: package_vm"
      - "status-success=ci/circleci: package_vm_cranelift"
      - "status-success=ci/circleci: contract_burner"
      - "status-success=ci/circleci: contract_hackatom"
      - "status-success=ci/circleci: contract_queue"
      - "status-success=ci/circleci: contract_reflect"
      - "status-success=ci/circleci: contract_staking"
      - "status-success=ci/circleci: fmt"
      - "status-success=ci/circleci: clippy"
      - "status-success=Windows"
      - "status-success=macOS"
    actions:
      merge:
        method: merge
        strict: false
