version: '3'

silent: true

vars:
  COSMWASM_CHECK_VERSION: 3.0.1

tasks:

  all:
    desc: Runs all checks
    summary: |
      Runs all viable checks for cosmwasm.
      Execute this task before pushing any changes.
      This task takes a significant amount of time to complete.
    cmds:
      - task: clean

  build:
    desc: Build all crates
    cmds:
      - cmd: cargo +1.82.0 build --workspace

  check-contracts:
    desc: Performs checks for all contracts
    cmds:
      - task: install-cosmwasm-check
      - cmd: ./devtools/check-contracts.sh

  check-contracts-parallel:
    desc: Performs checks in parallel for all contracts
    cmds:
      - task: install-cosmwasm-check
      - cmd: ./devtools/check-contracts.sh parallel

  check-contracts-fast:
    desc: Performs checks for all contracts without reinstalling cosmwasm-check tool
    cmds:
      - cmd: ./devtools/check-contracts.sh

  check-contracts-fast-parallel:
    desc: Performs checks in parallel for all contracts without reinstalling cosmwasm-check tool
    cmds:
      - cmd: ./devtools/check-contracts.sh parallel

  clean:
    desc: Removes all compiled artifacts
    cmds:
      - cmd: cargo clean
      - cmd: ./devtools/clean-contracts.sh

  cov-cosmwasm-check:
    desc: Generates code coverage report for cosmwasm-check in text format
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo +1.88.0 llvm-cov -p cosmwasm-check --no-cfg-coverage

  cov-badge-cosmwasm-check:
    desc: Generates the detailed code coverage badge for cosmwasm-check
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo +1.88.0 llvm-cov --no-cfg-coverage -p cosmwasm-check --json --summary-only | coverio

  cov-cosmwasm-core:
    desc: Generates code coverage report for cosmwasm-core in text format
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo +1.82.0 llvm-cov -p cosmwasm-core --no-cfg-coverage

  cov-badge-cosmwasm-core:
    desc: Generates the detailed code coverage badge for cosmwasm-core
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo +1.82.0 llvm-cov --no-cfg-coverage -p cosmwasm-core --json --summary-only | coverio

  cov-cosmwasm-crypto:
    desc: Generates code coverage report for cosmwasm-crypto in text format
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo +1.82.0 llvm-cov -p cosmwasm-crypto --no-cfg-coverage

  cov-badge-cosmwasm-crypto:
    desc: Generates the detailed code coverage badge for cosmwasm-crypto
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo +1.82.0 llvm-cov --no-cfg-coverage -p cosmwasm-crypto --json --summary-only | coverio

  cov-cosmwasm-std:
    desc: Generates code coverage report for cosmwasm-std in text format
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo +1.82.0 llvm-cov -p cosmwasm-std --no-cfg-coverage

  cov-badge-cosmwasm-std:
    desc: Generates the detailed code coverage badge for cosmwasm-std
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo +1.82.0 llvm-cov --no-cfg-coverage -p cosmwasm-std --json --summary-only | coverio

  install-cosmwasm-check:
    desc: Installs cosmwasm-check tool (released version and currently developed version)
    cmds:
      # Install recently released cosmwasm-check and rename it to cosmwasm-check-release
      - cmd: cargo +1.88.0 install cosmwasm-check@{{.COSMWASM_CHECK_VERSION}} --locked --force
      - cmd: mv ~/.cargo/bin/cosmwasm-check ~/.cargo/bin/cosmwasm-check-release
      # Install currently developed version of cosmwasm-check
      - cmd: cargo +1.88.0 install --path ./packages/check --locked --force
