// This code is @generated by cw-schema-codegen. Do not modify this manually.

{% if add_allow %}
#![allow(non_camel_case_types)]
{% endif %}

{% for doc in docs %}
    #[doc = "{{ doc }}"]
{% endfor %}

#[cosmwasm_schema::cw_serde]
pub enum {{ name }} {
{% for variant in variants %}
{% for doc in variant.docs %}
    #[doc = "{{ doc }}"]
{% endfor %}

{% match variant.serde_rename %}
{% when Some with (rename) %}
    #[serde(rename = "{{ rename }}")]
{% when None %}
{% endmatch %}

    {{ variant.name }}
{% match variant.ty %}
{% when TypeTemplate::Unit %}
{% when TypeTemplate::Tuple with (types) %}
        (
            {{ types|join(", ") }}
        )
{% when TypeTemplate::Named with { fields } %}
        {
        {% for field in fields %}
        {% for doc in field.docs %}
            #[doc = "{{ doc }}"]
        {% endfor %}
            {{ field.name }}: {{ field.ty }},
        {% endfor %}
        }
{% endmatch %}
        ,
{% endfor %}
}