// This code is @generated by cw-schema-codegen. Do not modify this manually.

{% if add_imports %}
import { z } from 'zod';
{% endif %}

/**
{% for doc in docs %}
    * {{ doc }}
{% endfor %}
 */

const {{ name }}Schema = z.union([
{% for variant in variants %}
    /**
    {% for doc in variant.docs %}
        * {{ doc }}
    {% endfor %}
     */

    {% match variant.ty %}
        {% when TypeTemplate::Unit %}
            z.object({ "{{ variant.name }}": z.null() }).or(z.literal("{{ variant.name }}")),
        {% when TypeTemplate::Tuple with (types) %}
            z.object({ "{{ variant.name }}": z.tuple([{{ types|join(", ") }}]) }),
        {% when TypeTemplate::Named with { fields } %}
            z.object({ "{{ variant.name }}": z.object({
                {% for field in fields %}
                    /**
                    {% for doc in field.docs %}
                        * {{ doc }}
                    {% endfor %}
                     */

                    {{ field.name }}: {{ field.ty }},
                {% endfor %}
            }) }),
    {% endmatch %}
{% endfor %}

{% if variants.len() == 0 %}
    never;
{% endif %}
]);

type {{ name }} = z.infer<typeof {{ name }}Schema>;

export { {{ name }}, {{ name }}Schema };
