name: "Install Rust toolchain"
description: "Install both `rustup` and a Rust toolchain"

inputs:
  toolchain:
    description: "Default toolchain to install"
    required: false
    default: "stable"

runs:
  using: node16
  main: "main.js"