# This code is @generated by cw-schema-codegen. Do not modify this manually.

import typing
import decimal
from pydantic import BaseModel, RootModel

class {{ name }}(RootModel):
    """{% for doc in docs %}
    {{ doc }}
    {% endfor %}"""

{% for variant in variants %}
{% match variant.ty %}
{% when TypeTemplate::Unit %}
    class {{ variant.name }}(RootModel):
        """{% for doc in variant.docs %}
        {{ doc }}
        {% endfor %}"""
        root: typing.Literal['{{ variant.name }}']
{% when TypeTemplate::Tuple with (types) %}
    class {{ variant.name }}(BaseModel):
        """{% for doc in variant.docs %}
        {{ doc }}
        {% endfor %}"""
        {{ variant.name }}: {% if types.len() == 1 %}typing.Union[{{ types[0] }}, typing.Tuple[{{ types[0] }}]]{% else %}typing.Tuple[{{ types|join(", ") }}]{% endif %}
{% when TypeTemplate::Named with { fields } %}
    class {{ variant.name }}(BaseModel):
        class __Inner(BaseModel):
            """{% for doc in variant.docs %}
            {{ doc }}
            {% endfor %}"""
            {% for field in fields %}
            {{ field.name }}: {{ field.ty }}
            """{% for doc in field.docs %}
            {{ doc }}
            {% endfor %}"""
            {% endfor %}
        {{ variant.name }}: __Inner
{% endmatch %}
{% endfor %}
    root: typing.Union[ {% for variant in variants %} {{ variant.name }}, {% endfor %} ]
