// This code is @generated by cw-schema-codegen. Do not modify this manually.

#![allow(non_camel_case_types)]



#[cosmwasm_schema::cw_serde]
pub enum rust_Hehehe {




    #[serde(rename = "A")]


    A


        ,




    #[serde(rename = "B")]


    B

        (
            u32
        )

        ,




    #[serde(rename = "C")]


    C

        {
        
        
            field: String,
        
        }

        ,

}
pub type TestType = rust_Hehehe;