// This code is @generated by cw-schema-codegen. Do not modify this manually.


#![allow(non_camel_case_types)]




#[cosmwasm_schema::cw_serde]
pub struct rust_utils_Foo


{





    foo_field_10: ::alloc::collections::BTreeMap<String, u32>,





    foo_field_11: (u32, String),





    foo_field_2: bool,





    foo_field_3: String,





    foo_field_4: i32,





    foo_field_5: u8,





    foo_field_6: Vec<String>,





    foo_field_7: ::core::option::Option<String>,





    foo_field_9: ::alloc::boxed::Box<String>,

}

pub type TestType = rust_utils_Foo;