// This code is @generated by cw-schema-codegen. Do not modify this manually.

package cwcodegen

{% for doc in docs %}
	// {{ doc }}
{% endfor %}
type {{ name }} struct {
	{% match ty %}
		{% when TypeTemplate::Unit %}
		{% when TypeTemplate::Tuple with (types) %}
			{{ todo!() }}
		{% when TypeTemplate::Named with { fields } %}
			{% for field in fields %}
				{% for doc in docs %}
					// {{ doc }}
				{% endfor %}
				{{ field.name|capitalize }} {{ field.ty }} `json:"{{ field.name }}"`
			{% endfor %}
	{% endmatch %}
}
