// This code is @generated by cw-schema-codegen. Do not modify this manually.

{% if add_package %}
package cwcodegen

import (
	"github.com/cosmos/cosmos-sdk/types"
)
{% endif %}

{% for doc in docs %}
	// {{ doc }}
{% endfor %}
{% match ty %}
{% when TypeTemplate::Unit %}
type {{ name }} struct{}
{% when TypeTemplate::Tuple with (types) %}
type {{ name }} []interface{} /* todo: replace with true tuples if i can think of it */
{% when TypeTemplate::Named with { fields } %}
type {{ name }} struct {
{% for field in fields %}
{% for doc in docs %}
	// {{ doc }}
{% endfor %}
	{{ field.name }} {{ field.ty }} `json:"{{ field.rename }}"`
{% endfor %}
}
{% endmatch %}
