[package]
name = "cosmwasm-crypto"
version.workspace = true
authors = ["Mauro Lacy <maurolacy@users.noreply.github.com>"]
edition = "2021"
description = "Crypto bindings for cosmwasm contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/crypto"
license = "Apache-2.0"

[features]
default = []
std = ["dep:bls12_381", "dep:rayon", "dep:sha2_v9", "dep:thiserror"]

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
derive_more = { version = "1.0.0-beta.6", default-features = false, features = ["display", "from"] }
k256 = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
ed25519-zebra = { version = "4.0.3", default-features = false }
digest = "0.10"
rand_core = "0.6"
# Not used directly, but needed to bump transitive dependency, see: https://github.com/CosmWasm/cosmwasm/pull/1899 for details.
ecdsa = "0.16.2"
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
pairing = "0.23.0"
bls12_381 = { version = "0.8.0", features = ["experimental"], optional = true }
rayon = { version = "1.9.0", optional = true }
sha2_v9 = { package = "sha2", version = "0.9.1", optional = true } # Must be compatible with bls12_381, see https://github.com/zkcrypto/bls12_381/issues/102
thiserror = { version = "1.0.26", optional = true }

[dev-dependencies]
base64 = "0.22.0"
base64-serde = "0.7.0"
criterion = "0.5.1"
rand_core = { version = "0.6", features = ["getrandom"] }
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0.40"
sha2 = "0.10"
sha3 = "0.10"
hex = { version = "0.4", features = ["serde"] }
hex-literal = "0.4.1"
english-numbers = "0.3"
glob = "0.3.1"

[[bench]]
name = "main"
harness = false
required-features = ["std"]
