[package]
name = "cosmwasm-crypto"
version.workspace = true
authors = ["Mauro Lacy <maurolacy@users.noreply.github.com>"]
edition = "2021"
description = "Crypto bindings for cosmwasm contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/crypto"
license = "Apache-2.0"

[features]
default = []
std = ["dep:thiserror"]

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
derive_more = { version = "1.0.0-beta.6", default-features = false, features = ["display", "from"] }
k256 = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
ed25519-zebra = { version = "4.0.3", default-features = false }
digest = "0.10"
rand_core = "0.6"
# Not used directly, but needed to bump transitive dependency, see: https://github.com/CosmWasm/cosmwasm/pull/1899 for details.
ecdsa = "0.16.2"
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
sha1 = "0.10.6"
thiserror = { version = "1.0.26", optional = true }

[dev-dependencies]
criterion = "0.5.1"
rand_core = { version = "0.6", features = ["getrandom"] }
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0.40"
sha2 = "0.10"
sha3 = "0.10"
hex = "0.4"
hex-literal = "0.4.1"
english-numbers = "0.3"

[[bench]]
name = "main"
harness = false
