[package]
name = "cyberpunk"
version = "0.0.0"
authors = ["Tomasz Kurcz <uint@users.noreply.github.com>"]
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# Add feature "cranelift" to default if you need 32 bit or ARM support
default = []
# Use cranelift backend instead of singlepass. This is required for development on 32 bit or ARM machines.
cranelift = ["cosmwasm-vm/cranelift"]
# For quicker tests, cargo test --lib. for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces", "cosmwasm-vm/backtraces"]

[dependencies]
cosmwasm-schema = { path = "../../packages/schema" }
cosmwasm-std = { path = "../../packages/std", default-features = false, features = ["abort", "cosmwasm_1_3"] }
drand-verify = "0.6.1"
# drand-verify = { git = "https://github.com/noislabs/drand-verify", branch = "arkworks", default-features = false, features = ["arkworks"] }
hex-literal = "0.4.1"
rust-argon2 = "2.0"
thiserror = "1.0.26"

[dev-dependencies]
criterion = "0.5.1"
cosmwasm-vm = { path = "../../packages/vm", default-features = false }
tempfile = "3.1.0"

[[bench]]
name = "host_vs_wasm"
harness = false
