[package]
name = "cw-schema-derive"
version.workspace = true
edition = "2021"

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
itertools = { version = "0.13.0", default-features = false }
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.72", features = ["full"] }
