name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:

permissions:
  contents: read

jobs:
  autofix-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update schemas
        run: ./devtools/update_schemas.sh

      # Get latest version from https://autofix.ci/setup
      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
