name: contracts

#on: [ push ]
on: [ pull_request_review ]

jobs:
  stable-rust:
    name: stable-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.82.0
          target: wasm32-unknown-unknown
          components: clippy, rustfmt
          cache-directories: |
            ${{ github.workspace }}/contracts/burner/target
            ${{ github.workspace }}/contracts/crypto-verify/target
            ${{ github.workspace }}/contracts/cyberpunk/target
            ${{ github.workspace }}/contracts/empty/target
            ${{ github.workspace }}/contracts/hackatom/target
            ${{ github.workspace }}/contracts/ibc2/target
            ${{ github.workspace }}/contracts/ibc-callbacks/target
            ${{ github.workspace }}/contracts/ibc-reflect/target
            ${{ github.workspace }}/contracts/ibc-reflect-send/target
            ${{ github.workspace }}/contracts/nested-contracts/target
            ${{ github.workspace }}/contracts/queue/target
            ${{ github.workspace }}/contracts/reflect/target
            ${{ github.workspace }}/contracts/replier/target
            ${{ github.workspace }}/contracts/staking/target
            ${{ github.workspace }}/contracts/virus/target

      - name: Verify contracts
        run: ./gh-actions/verify-contracts-stable.sh
