name: checks

on: [ push ]

jobs:
  stable-rel:
    name: ${{ matrix.dir }} (stable) ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
        dir: [ burner, crypto-verify, cyberpunk, empty, hackatom, ibc2, ibc-callbacks, ibc-reflect, ibc-reflect-send, nested-contracts, queue, reflect, replier, staking, virus ]
    defaults:
      run:
        shell: bash
        working-directory: contracts/${{ matrix.dir }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust for compiling cosmwasm-check
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87.0

      - name: Install cosmwasm-check
        run: cargo install cosmwasm-check@3.0.1

      - name: Print cosmwasm-check version
        run: cosmwasm-check --version

      - name: Install Rust for compiling contract
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.82.0
          target: wasm32-unknown-unknown
          cache-directories: |
            ${{ github.workspace }}/contracts

      - name: Build WASM binary
        run: cargo build --release --lib --locked --target wasm32-unknown-unknown

      - name: Check contract using cosmwasm-check
        run: cosmwasm-check target/wasm32-unknown-unknown/release/*.wasm

  stable-dev:
    name: ${{ matrix.dir }} (stable) ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
        dir: [ burner, crypto-verify, cyberpunk, empty, hackatom, ibc2, ibc-callbacks, ibc-reflect, ibc-reflect-send, nested-contracts, queue, reflect, replier, staking, virus ]
    defaults:
      run:
        shell: bash
        working-directory: contracts/${{ matrix.dir }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust for compiling cosmwasm-check
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87.0

      - name: Install cosmwasm-check
        run: cargo install --path ../../packages/check --locked

      - name: Print cosmwasm-check version
        run: cosmwasm-check --version

      - name: Install Rust for compiling contract
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.82.0
          target: wasm32-unknown-unknown
          cache-directories: |
            ${{ github.workspace }}/contracts

      - name: Build WASM binary
        run: cargo build --release --lib --locked --target wasm32-unknown-unknown

      - name: Check contract using cosmwasm-check
        run: cosmwasm-check target/wasm32-unknown-unknown/release/*.wasm

  nightly-rel:
    name: ${{ matrix.dir }} (nightly) ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dir: [ floaty ]
    defaults:
      run:
        shell: bash
        working-directory: ./contracts/${{ matrix.dir }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust for compiling cosmwasm-check
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87.0

      - name: Install cosmwasm-check
        run: cargo install cosmwasm-check@3.0.1

      - name: Print cosmwasm-check version
        run: cosmwasm-check --version

      - name: Print cosmwasm-check version
        run: cosmwasm-check --version

      - name: Install Rust for compiling contract
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2024-09-01 # This is a nightly channel for version 1.82.0
          target: wasm32-unknown-unknown
          cache-directories: |
            ${{ github.workspace }}/contracts

      - name: Build WASM binary
        run: RUSTFLAGS="-C target-feature=+nontrapping-fptoint" cargo build --release --lib --locked --target wasm32-unknown-unknown

      - name: Check contract using cosmwasm-check
        run: cosmwasm-check target/wasm32-unknown-unknown/release/*.wasm

  nightly-dev:
    name: ${{ matrix.dir }} (nightly) ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dir: [ floaty ]
    defaults:
      run:
        shell: bash
        working-directory: ./contracts/${{ matrix.dir }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust for compiling cosmwasm-check
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87.0

      - name: Install cosmwasm-check
        run: cargo install --path ../../packages/check --locked

      - name: Print cosmwasm-check version
        run: cosmwasm-check --version

      - name: Print cosmwasm-check version
        run: cosmwasm-check --version

      - name: Install Rust for compiling contract
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2024-09-01 # This is a nightly channel for version 1.82.0
          target: wasm32-unknown-unknown
          cache-directories: |
            ${{ github.workspace }}/contracts

      - name: Build WASM binary
        run: RUSTFLAGS="-C target-feature=+nontrapping-fptoint" cargo build --release --lib --locked --target wasm32-unknown-unknown

      - name: Check contract using cosmwasm-check
        run: cosmwasm-check target/wasm32-unknown-unknown/release/*.wasm
