name: schema

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [
          burner, crypto-verify, cyberpunk, empty, floaty, hackatom,
          ibc2, ibc-callbacks, ibc-reflect, ibc-reflect-send, nested-contracts,
          queue, reflect, replier, staking, virus
        ]
    defaults:
      run:
        working-directory: contracts/${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Delete old schema files
        run: rm -r ./schema || true

      - name: Generate new schema files
        run: cargo run --bin schema

      - name: Fail if the new schema files are not identical to the old schema files
        run: git diff --quiet ./schema
