name: workspace

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.82.0
          components: clippy, rustfmt
      - run: cargo fmt -- --check
      - run: cargo clippy -p cosmwasm-crypto --all-targets -- -D warnings
      - run: cargo clippy -p cosmwasm-derive --all-targets -- -D warnings
      - run: cargo clippy -p cosmwasm-std --all-targets --features std,iterator,staking,stargate -- -D warnings
      - run: cargo clippy -p cosmwasm-schema --all-targets -- -D warnings
      - run: cargo clippy -p cosmwasm-schema-derive --all-targets -- -D warnings
      - run: cargo clippy -p cw-schema --all-targets -- -D warnings
      - run: cargo clippy -p cw-schema-derive --all-targets -- -D warnings
      - run: cargo clippy -p cosmwasm-vm --all-targets --features iterator,stargate -- -D warnings
      - run: cargo clippy -p cosmwasm-check --all-targets -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.82.0
      - run: cargo build -p cosmwasm-crypto
      - run: cargo build -p cosmwasm-derive
      - run: cargo build -p cosmwasm-std
      - run: cargo build -p cosmwasm-std --no-default-features --features std
      - run: cargo build -p cosmwasm-std --features std,iterator,staking,stargate,cosmwasm_1_2
      - run: cargo build -p cosmwasm-schema
      - run: cargo build -p cosmwasm-schema-derive
      - run: cargo build -p cw-schema
      - run: cargo build -p cw-schema-derive
      - run: cargo build -p cosmwasm-vm --features iterator,stargate
      - run: cargo build -p cosmwasm-check
