[package]
name = "integration-virus"
version = "0.0.0"
authors = ["Dariusz Depta <DariuszDepta@users.noreply.github.com>"]
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "../src/lib.rs"

[dependencies]
virus = { path = ".." }
cosmwasm-schema = { version = "=3.0.11" }
cosmwasm-std = { version = "=3.0.11", features = ["cosmwasm_1_2"] }
schemars = "0.8.12"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.26"

[dev-dependencies]
cosmwasm-vm = { version = "=3.0.11", default-features = false, features = ["iterator"] }

# [patch.crates-io]
# cosmwasm-std = { path = "../../../packages/std", version = "=3.0.11" }
# cosmwasm-schema = { path = "../../../packages/schema", version = "=3.0.11" }
# cosmwasm-vm = { path = "../../../packages/vm", version = "=3.0.11" }
